name: Single-file deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: 6.0.x
  CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Publish single file
      run: dotnet publish -c ${{ env.CONFIGURATION }} -o publish -r win-x64 --self-contained true /p:PublishSingleFile=true
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: single-file-app
        path: publish\*.exe
